SignatureOperationStatus: |
  {
   "type": "object",
   "schema": "http://json-schema.org/draft-04/schema",
   "id": "SignatureOperationStatus",
   "description": "",
  
    "properties": {
     
        "AUTHORIZED":{
            "enum": [],
            "readonly": true,
            "description": ""
       },
 
        "SLOPE_BY_AUTHORIZING":{
            "enum": [],
            "readonly": true,
            "description": ""
       },
 
        "PENDING_SIGNATURE":{
            "enum": [],
            "readonly": true,
            "description": ""
       },
 
        "CANCEL_FIRST_SIGNATURE":{
            "enum": [],
            "readonly": true,
            "description": ""
       },
 
        "CANCEL_SECOND_SIGNATURE":{
            "enum": [],
            "readonly": true,
            "description": ""
       }
    }
  }