SignatureOperationFunctionType: |
  {
   "type": "object",
   "schema": "http://json-schema.org/draft-04/schema",
   "id": "SignatureOperationFunctionType",
   "description": "",
  
    "properties": {
     
        "SALARY_PAYMENT":{
            "enum": [],
            "readonly": true,
            "description": ""
       },
 
        "GROUPS":{
            "enum": [],
            "readonly": true,
            "description": ""
       },
 
        "INTERBANK_GROUPS":{
            "enum": [],
            "readonly": true,
            "description": ""
       },
 
        "INTERBANK_TRANSFER":{
            "enum": [],
            "readonly": true,
            "description": ""
       }
    }
  }