WireOperationDetail: |
  {
   "type": "object",
   "schema": "http://json-schema.org/draft-04/schema",
   "id": "WireOperationDetail",
   "description": "",
  
    "properties": {
            "receiverBank":{
            "type": "string",
            "description": "Banco destino"
        },
        "receiverAccount":{
            "type": "string",
            "description": "Cuenta deposito"
        },
        "receiverName":{
            "type": "string",
            "description": "Nombre tercero"
        },
        "paymentReason":{
            "type": "string",
            "description": "Motivo de pago"
        },
        "referenceNumber":{
            "type": "integer",
            "description": "Referencia numérica"
        },
        "nextBusinessDay":{
            "type": "string",
            "description": "Fecha hábil siguiente"
        }
    }
  }